config/routes.rb
Rails.application.routes.draw do
  resources :food_items do
    resources :orders
  end
  get 'menu' => 'home#menu'
  get 'contact_us' => 'home#contact_us'

  root "home#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :section
  validates :name, :price, presence: true
  has_many :orders

  def image_url_or_default
    image_url.presence || "http://loremflickr.com/680/480/#{name.split.first}"
  end


  def self.search(query)
    where("name like ?", "%#{query}%")
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :food_item
  validates :quantity, presence: true, numericality: true
  validates :name, presence: true
  validates :phone, presence: true
  validates :address, presence: true
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :food_items, dependent: :destroy
  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :description, :price, :section_id, :image_url)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contact_us
  end

  def menu
    @sections = Section.all

    # first get the full set depending on params
    if params[:section_id].present?
      @current_section = Section.find(params[:section_id])
      @food_items = @current_section.food_items
    elsif params[:search]
      @food_items = FoodItem.search(params[:search]).order("created_at DESC")
    else
      @food_items = FoodItem.all
    end

    # then sort
    if params[:sort_column]
      @food_items = @food_items.order("#{params[:sort_column]} #{params[:sort_direction]}")
    end

  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @item = FoodItem.find(params[:food_item_id])
    @order = @item.orders.build
  end

  def create
    @item = FoodItem.find(params[:food_item_id])
    @order = @item.orders.build order_params

    if @order.save
      render 'thank'
    else
      render 'new'
    end
  end

  def order_params
    params.require(:order).permit(:quantity, :name, :phone, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/food_items/_form.html.erb
<%= form_for(food_item) do |f| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :section_id %>
    <%= f.select :section_id, Section.all.map{|e| [e.name, e.id]} %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Food Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.section %></td>
        <td><%= food_item.image_url %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food Item', new_food_item_path %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food_item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @food_item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food_item.price %>
</p>

<p>
  <strong>Section:</strong>
  <%= @food_item.section %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @food_item.image_url %>
</p>

<%= link_to 'Edit', edit_food_item_path(@food_item) %> |
<%= link_to 'Back', food_items_path %>

app/views/home/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="modalId_<%= id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel"><%= name %></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= image_tag photo, class: 'menu-image' %>
        <p><%= desc %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/home/contact_us.html.erb
<h1><small>Contact</small> El Chico Timo</h1>

<div class="row">
  <div class="col-sm-6">
    <div class="card card-block">
      <addresss>
        <p><strong>El Chico Timo</strong>
        <br>123 Nguyen Ngoc Phuong
        <br>Phuong 19
        <br>Quan Binh Thanh
        <br>Ho Chi Minh
        <br>Vietnam</p>
        <p><strong>Phone:</strong> +84 123.456.7890
        <br><strong>Fax:</strong> +84 098.765.4321</p>
      </address>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="google-maps">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.277253506786!2d106.70591321461445!3d10.790064392312287!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317528b31177ea87%3A0xd7cbee887e0ac34!2zTmd1eeG7hW4gTmfhu41jIFBoxrDGoW5nLCBwaMaw4budbmcgMTksIELDrG5oIFRo4bqhbmgsIEjhu5MgQ2jDrSBNaW5oLCBWaWV0bmFt!5e0!3m2!1sen!2ssg!4v1487402679432" width="100%" height="auto" frameborder="0" style="border:0" allowfullscreen></iframe>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1><small>Restuarante</small> El Chico Timo</h1>

<%= link_to 'Menu', menu_path, class: 'btn btn-secondary' %>
<%= link_to 'Contact Us', contact_us_path, class: 'btn btn-secondary' %>

app/views/home/menu.html.erb
<h1>Menu</h1>

<% # menu section navigation %>
<div class="btn-group">

  <% @sections.each do |section| %>

    <%= link_to section.name, menu_path(section_id: section.id), class: "btn #{params[:section_id] == section.id.to_s ? 'btn-primary' : 'btn-secondary' }" %>

  <% end %>

  <%= link_to 'Full Menu', menu_path, class: "btn #{params[:section_id].presence ? 'btn-secondary' : 'btn-primary' }" %>

</div>


<% # display menu for selected section %>
<div class="card card-block">

  <% if @food_items.count >= 1 %>

    <% @food_items.each do |item| %>
      <%= render partial: 'modal', locals: {id: item.id, name: item.name, desc: item.description, photo: item.image_url_or_default} %>
    <% end %>

    <%= form_tag nil, method: 'get' do %>
      <div class="form-inline">
        <% # we want to keep existing params %>
        <% if params[:section_id].present? %>
          <%= hidden_field_tag :section_id, params[:section_id] %>
        <% end %>
        <% if params[:search].present? %>
          <%= hidden_field_tag :search, params[:search] %>
        <% end %>

        <% #and take new params as well %>
        <label>Sort by:</label>
        <%= select_tag :sort_column, options_for_select(["name", "price"]), class: 'form-control' %>
        <label> Direction:</label>
        <%= select_tag :sort_direction, options_for_select(["asc", "desc"]), class: 'form-control' %>
        <%= submit_tag "Sort", class: 'btn btn-primary' %>
      </div>
    <% end %>

    <table class="table">
      <thead>
        <tr>
          <th>Item</th>
          <th>Price</th>
          <th style="text-align:center">Image</th>
        </tr>
      </thead>
      <tbody>
        <% @food_items.each do |item| %>
            <tr>
              <td><%= item.name %></td>
              <td><%= number_with_delimiter(item.price, delimiter: ' ') %> VND</td>
              <td align="center"><%= image_tag item.image_url_or_default, class: 'menu-image' %></td>
              <td align="right">
                <%= content_tag(:button, 'Show Detail', class: 'btn btn-secondary', :data => {:toggle => 'modal', :target => "#modalId_#{item.id}"}) %>
                <%= link_to "Add to Order", new_food_item_order_path(item), class: 'btn btn-secondary' %>
              </td>
            </tr>
        <% end %>
      </tbody>
    </table>

  <% else %>

    <% if params[:search].present? %>

      <h5 class="card-title">Sorry, We couldn't find anything by that name.</h5>

    <% else %>

      <h5 class="card-title"><%= @current_section ? @current_section : '' %> Menu Coming Soon&hellip;</h5>

    <% end %>

  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <div class="container">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="<%= root_path %>">Home</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <!-- <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li> -->
      </ul>
      <%= form_tag(menu_path, :method => "get", class: "form-inline my-2 my-lg-0", id: "search-form") do %>
        <div class="input-append">
          <%= text_field_tag :search, params[:search], class: "form-control mr-sm-2", placeholder: "Search Menu" %>
          <!-- In order to have the "search" icon int the button, we need to use plain HTML instead
               of using a Rails form helper -->
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hw1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/new.html.erb
<h1>Order for <%= @item.name %></h1>

<%= form_for [@item, @order] do |f| %>
  <% if @order.errors.present? %>
    <div class="alert alert-danger"><%= @order.errors.full_messages.to_sentence %></div>
  <% end %>
  <div class="form-group">
    <%= f.label :quantity %>
    <%= f.number_field :quantity, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_area :address, class: 'form-control' %>
  </div>
  <%= f.submit nil, class: 'btn btn-primary' %>
<% end %>

app/views/orders/thank.html.erb
<%
  # calculations
  item_total = @order.quantity * @item.price
  order_total = item_total + 20000
%>

<h1>Thanks for your order, <%= @order.name %></h1>

<div class="card card-block">
  <h4 class="card-title">Here are your order details:</h4>
  <table class="table">
    <thead>
      <tr>
        <th>Item</th>
        <th style="text-align:right">Quantity</th>
        <th style="text-align:right">Price</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @item.name %></td>
        <td align="right"><%= @order.quantity %></td>
        <td align="right"><%= number_with_delimiter(item_total, delimiter: ' ') %> VND</td>
      </tr>
      <tr>
        <td>Delivery Fee</td>
        <td align="right"></td>
        <td align="right"><%= number_with_delimiter(20000, delimiter: ' ') %> VND</td>
      </tr>
    </tbody>
    <tfoot>
      <tr>
        <th>Order Total</th>
        <th style="text-align:right"></th>
        <th style="text-align:right"><%= number_with_delimiter(order_total, delimiter: ' ') %> VND</th>
      </tr>
    </tfoot>
  </table>
  <h4 class="card-title">Your order has been released to the kitchen and will be delivered to:</h4>
  <p><%= @order.name %> (<%= @order.phone %>)</p>
  <p><%= @order.address %></p>
  <br>
  <br>
  <p>Your order was placed at <%= @order.created_at.strftime("%l:%M%p") %>, <strong>Please allow at least 30 minutes for delivery</strong></p>

</div>

<div>
  <span>Return to: </span>
  <%= link_to 'Home', root_path, class: 'btn btn-secondary' %>
  <%= link_to 'Menu', menu_path, class: 'btn btn-secondary' %>
</div>